title: VTK-m
description: A toolkit of scientific visualization algorithms for emerging processor architectures
baseurl: '/'
markdown: kramdown

download_link: https://gitlab.kitware.com/vtk/vtk-m/-/releases

# Footer Info
footer_license: License info goes here
footer_links:
  - title: Kitware
    url: 'https://kitware.com'
  - title: Privacy Policy
    url: 'https://www.kitware.com/privacy/#privacy-policy'
  - title: Contact
    url: 'https://www.kitware.com/contact-us/'

defaults:
  - scope:
      path: ''
    values:
      layout: 'default'

include:
  - '_pages'
  # Cloudflare Pages requires _redirects to be in the output directory
  - '_redirects'

exclude:
  - '*.config.js'
  - 'package*.json'
  - assets
  - node_modules
  - vendor

plugins: ['jekyll/scholar']

scholar:
  source: _publications
  bibliography: pubs.bib
  style: apa-annotated-bibliography
