title: VTK-m
description: A toolkit of scientific visualization algorithms for emerging processor architectures
baseurl: '/'

# Footer Info
footer_license: License info goes here
footer_links:
  - title: Kitware
    url: 'https://kitware.com'
  - title: Privacy Policy
    url: 'https://m.vtk.org/index.php/VTKM:Privacy_policy'
  - title: Disclaimers
    url: 'https://m.vtk.org/index.php/VTKM:General_disclaimer'
  - title: Contact
    url: '#'

# Publications
pubs_title: VTK-m Publications
pubs_blurb: Please use the first paper when referencing VTK-m in scientific publications.
pubs_buttons:
  - label: Presentations
    url: https://m.vtk.org/index.php/Presentations
  - label: Logos
    url: https://m.vtk.org/index.php/Logos

defaults:
  - scope:
      path: ''
    values:
      layout: 'default'

exclude:
  - '*.config.js'
  - 'package*.json'
  - assets
  - node_modules

plugins: ['jekyll/scholar']

scholar:
  source: _publications
  bibliography: pubs.bib
