title: VTK-m
description: A toolkit of scientific visualization algorithms for emerging processor architectures
baseurl: '/'

defaults:
  - scope:
      path: ''
    values:
      layout: 'default'

exclude:
  - '*.config.js'
  - 'package*.json'
  - assets
  - node_modules
