[build]
  publish = "_site/"
  command = "npm run prod && jekyll build"

# Previously, Doxygen docs were hosted under "m.vtk.org/documentation/",
# so provide a redirect to transition any old links
[[redirects]]
  # Place this more specific rule first, so it's matched first
  from = "/documentation/nightly/*"
  to = "https://docs-m.vtk.org/nightly/:splat"

[[redirects]]
  # Otherwise, consider "latest" to be the canonical version
  from = "/documentation/*"
  to = "https://docs-m.vtk.org/latest/:splat"
