[build]
  publish = "_site/"
  command = "npm run prod && jekyll build"

[[redirects]]
  # Previously, Doxygen docs were hosted under "m.vtk.org/documentation/",
  # so provide a redirect to transition any old links
  from = "/documentation/*"
  to = "https://docs-m.vtk.org/documentation/:splat"
